# Generated by Django 5.1.7 on 2025-03-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mob', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('gen', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], default='male', max_length=10)),
            ],
        ),
    ]
