# Generated by Django 5.1.7 on 2025-03-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('option1', models.CharField(max_length=80)),
                ('option2', models.CharField(max_length=80)),
                ('option3', models.CharField(max_length=80)),
                ('option4', models.CharField(max_length=80)),
                ('answer', models.CharField(max_length=80)),
            ],
        ),
    ]
