# Generated by Django 5.1.7 on 2025-03-29 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='paper', to='myapp.subject'),
            preserve_default=False,
        ),
    ]
