# Generated by Django 5.1.7 on 2025-03-29 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_paper_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='myapp.course'),
        ),
    ]
