# Generated by Django 5.1.7 on 2025-03-29 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_paper_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='paper',
            new_name='papermodel',
        ),
    ]
