# Generated by Django 5.1.7 on 2025-03-29 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_paper_papermodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='papermodel',
            new_name='paper',
        ),
    ]
