# Generated by Django 5.1.7 on 2025-04-01 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_subject_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='course',
        ),
    ]
