# Generated by Django 4.2.20 on 2025-04-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_subject_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='resultmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('subject_id', models.BigIntegerField()),
                ('subject_name', models.CharField(max_length=80)),
                ('score', models.BigIntegerField()),
                ('total_questions', models.BigIntegerField()),
                ('result_percentage', models.BigIntegerField()),
            ],
        ),
    ]
