# Generated by Django 4.2.20 on 2025-04-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_course_sub'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultmodel',
            name='course_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='sub',
            field=models.ManyToManyField(related_name='subjects', to='myapp.subject'),
        ),
    ]
